import turtle

def house():
    turtle.fillcolor("purple")
    turtle.begin_fill()
    turtle.fd(100)
    turtle.right(90)
    turtle.fd(100)
    turtle.right(90)
    turtle.fd(100)
    turtle.right(90)
    turtle.fd(100)
    turtle.end_fill()
    turtle.fillcolor("red")
    turtle.begin_fill()
    turtle.right(40)
    turtle.fd(80)
    turtle.right(100)
    turtle.fd(80)
    turtle.end_fill()
house()
turtle.up()
turtle.goto(200,0)
turtle.down()
turtle.seth(0)
house()
turtle.up()
turtle.goto(400,0)
turtle.down()
turtle.seth(0)
house()
turtle.up()
turtle.goto(-200,0)
turtle.down()
turtle.seth(0)
house()

turtle.exitonclick()
